server:
  port: 8080

session:
  key: S0MekEy321

#logging:
#  level:
#    org:
#      springframework:
#        security:
#          TRACE
#    com:
#      example:
#        client:
#          DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/universitydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            scope:
              - user:email
              - read:user
          google:
            client-id:
            client-secret:
            scope:
              - openid
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true