server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    aws:
      region:
        static: eu-central-1

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github.client-id}
            client-secret: ${github.client-secret}
            scope:
              - user:email
              - read:user
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - openid
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9000
  info:
    env:
      enabled: true

info:
  application:
    name: security-crud-flow
    description: The project represents a university system in which the user has a certain role.
    author: Yan Samokar
    version: '@project.version@'
